/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IMulticallAccount } from "./IMulticallAccount";

export class IMulticallAccountFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMulticallAccount {
    return new Contract(address, _abi, signerOrProvider) as IMulticallAccount;
  }
}

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "to",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "value",
            type: "uint256",
          },
          {
            internalType: "bytes",
            name: "data",
            type: "bytes",
          },
        ],
        internalType: "struct IMulticall.Call[]",
        name: "_calls",
        type: "tuple[]",
      },
    ],
    name: "multicall",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];
