/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IMulticallAccountInterface extends ethers.utils.Interface {
  functions: {
    "multicall(tuple[])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "multicall",
    values: [{ to: string; value: BigNumberish; data: BytesLike }[]]
  ): string;

  decodeFunctionResult(functionFragment: "multicall", data: BytesLike): Result;

  events: {};
}

export class IMulticallAccount extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IMulticallAccountInterface;

  functions: {
    multicall(
      _calls: { to: string; value: BigNumberish; data: BytesLike }[],
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "multicall(tuple[])"(
      _calls: { to: string; value: BigNumberish; data: BytesLike }[],
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;
  };

  multicall(
    _calls: { to: string; value: BigNumberish; data: BytesLike }[],
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "multicall(tuple[])"(
    _calls: { to: string; value: BigNumberish; data: BytesLike }[],
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  callStatic: {
    multicall(
      _calls: { to: string; value: BigNumberish; data: BytesLike }[],
      overrides?: CallOverrides
    ): Promise<void>;

    "multicall(tuple[])"(
      _calls: { to: string; value: BigNumberish; data: BytesLike }[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    multicall(
      _calls: { to: string; value: BigNumberish; data: BytesLike }[],
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "multicall(tuple[])"(
      _calls: { to: string; value: BigNumberish; data: BytesLike }[],
      overrides?: PayableOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    multicall(
      _calls: { to: string; value: BigNumberish; data: BytesLike }[],
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "multicall(tuple[])"(
      _calls: { to: string; value: BigNumberish; data: BytesLike }[],
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;
  };
}
